name: CI

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          environments: dev codegen
      - name: Generate parser
        run: pixi run codegen
      - name: Test grammar
        run: pixi run test
      - name: Test Python binding
        run: pixi run --environment dev pytest bindings/python/tests/
